root = "."
tmp_dir = "bin"

[build]
  bin = "./bin/vsoutook-app"
  cmd = "go build -o ./bin/vsoutook-app ."
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "data"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true
  delay = 1000
  kill_delay = 10

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
