HTTP_PORT: 4100
DATABASE_URL: postgres://#{database_username}:#{database_password}@localhost:5432/#{database_name}?sslmode=disable
DATABASE_TESTURL: postgres://#{database_username}:#{database_password}@localhost:5432/#{database_name}?sslmode=disable
REDIS_URL: redis://localhost:6379/5
ALIYUN_KEY: xxx
ALIYUN_SECRET: xxx
