HTTP_PORT: 8091
DATABASE_URL: postgres://postgres:postgresql@localhost:5432/vsoutlook?sslmode=disable
DATABASE_TESTURL: postgres://postgres:postgresql@localhost:5432/vsoutlook?sslmode=disable
REDIS_URL: redis://localhost:6379/5
SESSION_SECRET: vcsuaswyoizzzltkbdwjpufuklubvuxg
STATIC_PATH: /home/vsoutlook/vsoutlook-app-2/frontend
CLUST_HOST: http://192.168.1.67:8080
CHART_PKG: local/foo
