name: Build app server
run-name: "${{ github.actor }}: Build app server"
on:
  push:
    paths: ["server/**"]
  workflow_dispatch:
jobs:
  build-app-server:
    name: build app server
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Docker login
        run: |
          docker login ${{ secrets.A_REGISTRY_HOST }} -u ${{ secrets.A_REGISTRY_PWD }}

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV

      - name: run server build docker
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          cd server; bash build-docker.sh
